config/routes.rb
HouseCleaning::Application.routes.draw do
  get "registraion/new"
  get "home/index"

   root 'home#index'

  get 'registraion/new' => 'registraion#new',:as =>  :new_user
  get 'session/new' => 'session#new' , :as => :existing_user
  get "/auth/:provider/callback" => "session#create"
  get '/:id' => 'home#welcome', :as => :welcome_page
  post '/:id' => 'home#update_password' , :as => :password_update
  post '/registrations' => 'registraion#create',:as =>  :user_create

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create


  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def welcome
    @update_password = User.where(:id => params[:id]).first
  end


end

app/controllers/registraion_controller.rb
class RegistraionController < ApplicationController
  def new
    @registration = User.new
  end

  def create
    @registration = User.new
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    
  end

  def create
    auth = request.env['omniauth.auth']
     if auth and params[:provider]
        @authhash = Hash.new # {"email" => '', "name" => '', "uid" =>'',  "provider" =>''}
        @authhash[:provider] = auth['provider'] or ''
          if params[:provider] == 'facebook'
            @authhash[:email] = auth['extra']['raw_info']['email'] or ''
            @authhash[:first_name] =  auth['extra']['raw_info']['first_name'] or ''
            @authhash[:last_name] =  auth['extra']['raw_info']['last_name'] or ''
            @authhash[:name] =  auth['extra']['raw_info']['last_name'] or ''
            @authhash[:gender] =  auth['extra']['raw_info']['gender'] or ''
            @authhash[:name] =  auth['extra']['raw_info']['name'] or ''
            @authhash[:facebook_id] =  auth['extra']['raw_info']['id'].to_s or ''
            @authhash[:profile_picture] =  auth['info']['image'].to_s or ''

            @authhash[:fb_token] = auth['credentials']['token'] or nil
          elsif ['google'].index(params[:provider]) != nil
            @authhash[:email] =  auth['info']['email'] or ''
            @authhash[:name] = auth['info']['name'] or ''
            @authhash[:uid] = auth['uid'].to_s or ''
          else
         # TODO: message that it is not supported
          render root_url
          return
          end
          @fb_user  = User.where(:facebook_id => @authhash[:facebook_id]).first
          if @fb_user.present?
            @fb_user.update_attributes(:fb_token =>@authhash[:fb_token], :first_name => @authhash[:first_name],:last_name => @authhash[:last_name],:gender => @authhash[:gender],:email=>@authhash[:email],:name => @authhash[:name],:facebook_id=>@authhash[:facebook_id],:provider=>@authhash[:provider])
            if @fb_user.save
              session[:facebook_id] = @fb_user.facebook_id
              session[:user_id] = @fb_user.id
              redirect_to welcome_page_path(session[:user_id])
            end
          else
            @user = User.create
            @user.update_attributes(:fb_token =>@authhash[:fb_token], :first_name => @authhash[:first_name],:last_name => @authhash[:last_name],:gender => @authhash[:gender],:email=>@authhash[:email],:name => @authhash[:name],:facebook_id=>@authhash[:facebook_id],:provider=>@authhash[:provider])
            if @user.save
              session[:facebook_id] = @authhash[:facebook_id]
              session[:user_id] = @user.id
              redirect_to welcome_page_path(session[:user_id])
            end
            puts"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%else condision #{@fb_user.inspect}"
          end
         
    puts"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#{@authhash.inspect}"
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registraion_helper.rb
module RegistraionHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/home/index.html.erb
<%= link_to "Sign-up", new_user_path  %>
<%= link_to "login" , existing_user_path %>

<%= t :Just %> <a href="<%= $URL%>/auth/facebook">Login With Facebook</a>

app/views/home/welcome.html.erb
<%#*<h3>Password Create</h3>%>

<%#= form_for @update_password, :as => :user_pssword, :url => password_update_path, :method => "post" do |f| %>

<%#*<p>%>
<%#*<div class="field">%>
  <%#*<label>Password</label><br/>%>
  <%#= f.password_field :password, :placeholeder => "password" %>
<%#*</div>%>
<%#*</p>%>

<%#*<p>%>
<%#*<div class="field">%>
  <%#*<label>Password Confirmation</label><br/>%>
  <%#= f.password_field :password_confirmation, :placeholeder => "password" %>
<%#*</div>%>
<%#*</p>%>
         <%#=  f.hidden_field :user_id, :value=>session[:user_id] %>
<%#*<p>%>
  <%#= f.submit "Update Password" %>
<%#*</p>%>

<%# end  %>

<h3>welcome <%= @update_password.name %></h3>

<h2>Account Info</h2>
<%= form_for @update_password, :as => :update, :url => password_update_path, :id => @update_password.id, :method => "post" do |f|%>
  <p>
<div class="field">
  <label>First Name</label><br/>
 <%= f.text_field :first_name %>
</div>
</p>
 <p>
<div class="field">
  <label>Last Name</label><br/>
 <%= f.text_field :last_name %>
</div>
</p>
 <p>
<div class="field">
  <label>Gender</label><br/>
 <%= f.text_field :gender %>
</div>
</p>
 <p>
<div class="field">
  <label>Address</label><br/>
 <%= f.text_field :address %>
</div>
</p>

<p>
<div class="field">
  <label>City</label><br/>
 <%= f.text_field :city %>
</div>
</p>

         <%=  f.hidden_field :user_id, :value=>session[:user_id] %>
<p>
  <%= f.submit "Update Password" %>
</p>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HouseCleaning</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/registraion/new.html.erb
<h3>Registration Here </h3>

<%= form_for @registration, :as => :user, :url => user_create_path , :method => "post", :html => {:multipart => true} do |f| %>

<p>
<div class="field">
  <label>First Name:</label>
  <%= f.text_field :first_name %>
</div>
</p>

<p>
<div class="field">
  <label>Last Name:</label>
  <%= f.text_field :last_name %>
</div>
</p>


<p>
<div class="field">
  <label>Gender:</label>
  <%= f.text_field :gender %>
</div>
</p>


<p>
<div class="field">
  <label>City:</label>
  <%= f.text_field :first_name %>
</div>
</p>


<p>
<div class="field">
  <label>Country</label>
  <%= f.text_field :country %>
</div>
</p>


<p>
<div class="field">
  <label>Country</label>
  <%= f.text_field :state %>
</div>
</p>


<p>
<div class="field">
  <label>Address:</label>
  <%= f.text_field :address %>
</div>
</p>


<p>
<div class="field">
  <label>Zip-code: </label>
  <%= f.text_field :zipcode %>
</div>
</p>


<p>
<div class="field">
  <label>Profile  Picture</label>
  <%= f.text_field :profile_picture %>
</div>
</p>

<p>
<div class="field">
  <%= f.submit "Register" %>
</div>
</p>

<% end %>